; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
board_build.partitions = min_spiffs.csv
build_type = debug
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = 
	-D CONFIG_ASYNC_TCP_TASK_STACK_SIZE=4096
	-D CONFIG_ASYNC_TCP_RUNNING_CORE=1
	-D CONFIG_ESP32_WIFI_SW_COEXIST_ENABLE=1
lib_deps = 
	bblanchon/ArduinoJson

[env:mini]
extends = env

board = esp32-s3-devkitc-1

board_build.flash_size = 16MB
board_build.psram = opi
board_build.partitions = huge_app.csv

board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi

build_flags =
    ${env.build_flags}
    -DWAVELET_MINI
    -DFEATURE_DISPLAY
    -DFEATURE_BATTERY
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    ${env.lib_deps}
    ; https://github.com/nayuki/QR-Code-generator.git
    lvgl/lvgl @ 8.4.0

build_src_filter =
    +<main.cpp>
    +<mini/**>
    +<spotify_controller/**>
    ; +<screens/**>
    ; -<audio/**>
    ; -<core/**>
    ; -<input/**>
    ; -<ble/**>
    ; -<web/**>
    ; -<wifi/**>



[env:regular]
extends = env

build_flags =
    ${env.build_flags}
    -DWAVELET_REGULAR
    -DFEATURE_BATTERY

lib_deps =
    ${env.lib_deps}
    https://github.com/pschatzmann/ESP32-A2DP.git

[env:max]
extends = env

build_flags =
    ${env.build_flags}
    -DWAVELET_MAX
    -DFEATURE_WIFI
    -DFEATURE_DISPLAY
    -DFEATURE_ASSISTANT
    -DFEATURE_DLNA
    -DFEATURE_BATTERY

lib_deps =
    ${env.lib_deps}

